name: Nix Build & Test

on:
  push:
    branches: [ 'users/VS-*/**', main ]
  pull_request:
    branches: [ 'users/VS-*/**', main ]

permissions:
  contents: read
  packages: read

jobs:
  nix-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      actions: read
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.GIT_TOKEN }}
      
      - name: Install Nix
        uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GIT_TOKEN }}
      
      - name: Setup Cachix
        uses: cachix/cachix-action@v12
        with:
          name: ryzengrind-nix-config
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: false
          extraPullNames: nix-community, ryzengrind
      
      - name: Test Nix Shell
        run: |
          # Verify nix-shell loads correctly
          nix-shell shell.nix --run "echo 'Nix shell loads successfully'"
          
          # Test if required tools are available in nix-shell
          nix-shell shell.nix --run "gcc --version"
          nix-shell shell.nix --run "make --version"
          nix-shell shell.nix --run "git --version"
          nix-shell shell.nix --run "gdb --version"
          nix-shell shell.nix --run "valgrind --version"

  build-test:
    needs: nix-build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      actions: read
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.GIT_TOKEN }}
      
      - name: Install Nix
        uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GIT_TOKEN }}
      
      - name: Build Project
        run: |
          nix-shell shell.nix --run "make all"
          
      - name: Verify Build Artifacts
        run: |
          nix-shell shell.nix --run "test -f jeopardy"
          
      - name: Test Clean Target
        run: |
          nix-shell shell.nix --run "make clean"
          nix-shell shell.nix --run "test ! -f jeopardy"
          
      - name: Upload Build Artifacts
        if: success()
        uses: actions/upload-artifact@v4.1.1
        with:
          name: jeopardy-game
          path: |
            jeopardy
            *.o
          retention-days: 7

  code-analysis:
    needs: nix-build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      actions: read
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.GIT_TOKEN }}
      
      - name: Install Nix
        uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GIT_TOKEN }}
        
      - name: Static Analysis
        run: |
          nix-shell shell.nix --run "gcc -fanalyzer -Wall -Wextra -std=c99 -c *.c" 